from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def render_report(verdict: dict[str, Any]) -> str:
    scores = verdict["scores"]
    rationale = "".join(
        f"<li>{html.escape(str(item))}</li>" for item in verdict.get("rationale", [])
    )
    conditions = "".join(
        f"<li>{html.escape(str(item))}</li>" for item in verdict.get("conditions", [])
    )
    score_cards = "".join(
        f"<article><strong>{html.escape(name.replace('_', ' ').title())}</strong>"
        f"<span>{int(value)}/25</span></article>"
        for name, value in scores.items()
    )
    recommendation = html.escape(str(verdict["recommendation"]))
    total = int(verdict["total"])
    case = html.escape(str(verdict.get("case", "Product due diligence")))
    dissent = html.escape(str(verdict.get("dissent", "None")))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Verdict Room Report</title>
  <style>
    :root {{ color-scheme: dark; font-family: Inter, system-ui, sans-serif; }}
    body {{ margin: 0; background: #090b10; color: #eef1f7; }}
    main {{ width: min(920px, calc(100% - 32px)); margin: 48px auto; }}
    header, section {{ background: #121722; border: 1px solid #263044;
      border-radius: 20px; padding: 28px; margin-bottom: 18px; }}
    .eyebrow {{ color: #8da2c8; letter-spacing: .14em; text-transform: uppercase; }}
    h1 {{ font-size: clamp(34px, 8vw, 72px); margin: 8px 0; }}
    .verdict {{ color: #75e6a4; }}
    .score-grid {{ display: grid; grid-template-columns: repeat(auto-fit,minmax(180px,1fr));
      gap: 12px; }}
    article {{ display: flex; justify-content: space-between; align-items: baseline;
      gap: 16px; background: #0c111a; border-radius: 14px; padding: 18px; }}
    article strong {{ line-height: 1.3; }}
    article span {{ color: #75e6a4; font-weight: 800; white-space: nowrap; }}
    li {{ margin: 10px 0; line-height: 1.5; }}
    footer {{ color: #8da2c8; text-align: center; padding: 24px; }}
  </style>
</head>
<body><main>
  <header>
    <div class="eyebrow">Band-native multi-agent due diligence</div>
    <h1>{total}/100</h1>
    <h2 class="verdict">{recommendation}</h2>
    <p>{case}</p>
  </header>
  <section><h2>Scorecard</h2><div class="score-grid">{score_cards}</div></section>
  <section><h2>Rationale</h2><ul>{rationale}</ul></section>
  <section><h2>Purchase conditions</h2><ul>{conditions or "<li>None</li>"}</ul></section>
  <section><h2>Dissent</h2><p>{dissent}</p></section>
  <footer>Generated by Verdict Room agents collaborating through Band.</footer>
</main></body></html>"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("verdict", type=Path, help="Path to verdict JSON")
    parser.add_argument(
        "--output", type=Path, default=PROJECT_ROOT / "docs" / "report.html"
    )
    args = parser.parse_args()
    verdict = json.loads(args.verdict.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_report(verdict), encoding="utf-8")
    print(args.output)


if __name__ == "__main__":
    main()
